
INSERT INTO PRODUCT
    VALUES 
    (1,
    'Apple MacBook Pro MD101 Silver Notebook merupakan MacBook Pro berukuran 13.3 inch dengan resolusi 1280 x 800 piksel.',
    'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full/apple_apple-macbook-pro-md101-silver_full04.jpg',
    15000000.00,
    'Garansi 1 Tahun Apple Internasional',
    'Apple MacBook Pro MD101 Silver Notebook : Operating System Mac OS X 10.8',
    'Apple MacBook Pro MD101 Silver Notebook'),
    (12242,
    'Apple MacBook Pro MD101 Silver Notebook merupakan MacBook Pro berukuran 13.3 inch dengan resolusi 1280 x 800 piksel.',
    'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full/apple_apple-macbook-pro-md101-silver_full04.jpg',
    15000000.00,
    'Garansi 1 Tahun Apple Internasional',
    'Apple MacBook Pro MD101 Silver Notebook : Operating System Mac OS X 10.8',
    'Apple MacBook Pro MD101 Silver Notebook'),
    (162926,
    'Apple Macbook Air MJVM2ID/A Laptop merupakan laptop yang memiliki desain yang begitu tipis dan ringan lebih kecil dari versi kakanya MJVE2ID/A. MacBook Air berukuran 11.6 inci ini memiliki ketebalan hanya 17 milimeter dan berat hanya 1 kg',
    'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full/blibli_apple-macbook-pro-13-3-2-5ghz-i5-4gb-500gb_full01.jpg',
    21000000.00,
    'Garansi 1 Tahun Apple Internasional',
    'Processor Type : Intel Core i5. Processor Onboard : Intel Core i5 1.6GHz (L3 Cache 3MB Shared). Memory : 4GB DDR3',
    'Apple Macbook Air MJVM2IDA Laptop'),
    (162926,
    'Apple Macbook Air MJVM2ID/A Laptop merupakan laptop yang memiliki desain yang begitu tipis dan ringan lebih kecil dari versi kakanya MJVE2ID/A. MacBook Air berukuran 11.6 inci ini memiliki ketebalan hanya 17 milimeter dan berat hanya 1 kg',
    'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full/blibli_apple-macbook-pro-13-3-2-5ghz-i5-4gb-500gb_full01.jpg',
    21000000.00,
    'Garansi 1 Tahun Apple Internasional',
    'Processor Type : Intel Core i5. Processor Onboard : Intel Core i5 1.6GHz (L3 Cache 3MB Shared). Memory : 4GB DDR3',
    'Apple Macbook Air MJVM2IDA Laptop'),
    (484625,
    'Apple Macbook Retina Display Gold Notebook [ 12inch/ 256GB] adalah notebook tertipis dan teringan kami.  Dengan 12-inci Retina display yang menakjubkan,
     keyboard Apple dirancang dan semua-baru Angkatan Touch trackpad.',
    'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full/apple_macbook-12--retina-display-256gb-gold_full05.jpg',
    21000000.00,
    'Garansi 1 Tahun Apple Internasional',
    'Processor Type : Intel Core i5. Processor Onboard : Intel Core i5 1.6GHz (L3 Cache 3MB Shared). Memory : 4GB DDR3',
    'Apple Macbook Retina Display Gold Notebook 12inch 256GB');

